In [76]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [77]:
iris=pd.read_csv('data_iris.csv')

In [78]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [79]:
iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [80]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [81]:
iris.isna()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [82]:
iris.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [83]:
iris.isna().apply(pd.value_counts).T

False
Id               150
SepalLengthCm    150
SepalWidthCm     150
PetalLengthCm    150
PetalWidthCm     150
Species          150

In [84]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [85]:
iris.shape

(150, 6)

In [86]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

le=LabelEncoder()
enc=OneHotEncoder(sparse=False)
lb=LabelBinarizer()



In [87]:
iris['Species']=le.fit_transform(iris['Species'].values).astype('float')

iris.Species

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: Species, Length: 150, dtype: float64

In [88]:
class_arr=iris.Species.values
class_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [89]:
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2      0.0
1      2            4.9           3.0            1.4           0.2      0.0
2      3            4.7           3.2            1.3           0.2      0.0
3      4            4.6           3.1            1.5           0.2      0.0
4      5            5.0           3.6            1.4           0.2      0.0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3      2.0
146  147            6.3           2.5            5.0           1.9      2.0
147  148            6.5           3.0            5.2           2.0      2.0
148  149            6.2           3.4            5.4           2.3      2.0
149  150            5.9           3.0            5.1           1.8      2.0

[150 rows x 6 columns]

In [90]:
class1=iris.Species.values.reshape(len(iris),1)
class1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [91]:
onehotvector=enc.fit_transform(class1)


In [92]:
onehotvector

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [113]:
class1=iris.Species.values.reshape(len(iris),1)
enc.fit_transform(class1)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
#InDependent variable / features/paramenter/column
X=iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]

In [94]:
#Dependent variable / features/paramenter/column
y=iris[['Species']]

In [95]:
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [96]:
y.head()

Species
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,train_size=0.7,random_state=1)

In [99]:
X_train.shape

(105, 4)

In [100]:
X_test.shape

(45, 4)

In [101]:
y_train.shape

(105, 1)

In [102]:
y_test.shape

(45, 1)

In [103]:
y.shape

(150, 1)

In [104]:
from sklearn.linear_model import LinearRegression

In [105]:
#Object creaton
linearReg_model=LinearRegression()

In [106]:
#training the model using .fit() function
linearReg_model.fit(X_train,y_train)

LinearRegression()

In [116]:
#training the model using .fit() function
linearReg_model.fit(X_train,y_train)

LinearRegression()

In [117]:
#Object creaton
model=LinearRegression()

In [119]:
#testing the data/model or predicting the data or predicting the model (y^)
y_pred=linearReg_model.predict(X_test)
y_pred

array([[-0.29548424],
       [ 0.8682574 ],
       [ 1.15876676],
       [-0.07882365],
       [ 1.83980587],
       [ 1.42343363],
       [ 1.77637713],
       [ 0.17646056],
       [ 0.05631021],
       [ 1.97058911],
       [ 1.25191413],
       [ 0.04984515],
       [ 1.88913028],
       [ 1.28620262],
       [ 1.36722933],
       [ 0.02329842],
       [ 1.09351985],
       [ 1.4530912 ],
       [-0.02053318],
       [-0.13584839],
       [ 1.28567845],
       [ 1.49541773],
       [ 1.48218035],
       [-0.04953028],
       [ 1.75097812],
       [ 1.19979245],
       [-0.16524247],
       [-0.00273279],
       [ 1.25761801],
       [ 1.6618386 ],
       [ 1.3289175 ],
       [ 1.92753418],
       [ 1.05194585],
       [ 1.93835399],
       [ 2.05607128],
       [-0.09679267],
       [ 1.20390785],
       [-0.11142296],
       [ 1.2923714 ],
       [ 1.78399855],
       [ 1.82395129],
       [-0.03852635],
       [ 1.51960382],
       [ 1.80915238],
       [ 1.17136781]])

In [120]:
from sklearn.metrics import r2_score

In [121]:
#counting R2 score by
r2_score(y_test,y_pred)*100

90.82844376254667

In [123]:
linearReg_model.score(X_test,y_test)*100

90.82844376254667

In [127]:
#Adjusted R_square
adj_r2_score=1-(1-linearReg_model.score(X_test,y_test))*len((y_train)-1)/(len(y_train)-y_test.shape[1]-1)
adj_r2_score

0.906503552919165

In [128]:
adj_r2_score*100

90.6503552919165

In [129]:
from sklearn.metrics import mean_squared_error

In [130]:
mean_squared_error(y_test,y_pred)

0.05498404578897949