In [1]:
import numpy as np

In [2]:
a = [5,2,7,4,1]

In [3]:
a

[5, 2, 7, 4, 1]

In [4]:
type(a)

list

In [5]:
len(a)

5

In [7]:
#Converting a list into an array
b = np.array(a)

In [8]:
b

array([5, 2, 7, 4, 1])

In [9]:
type(b)

numpy.ndarray

In [10]:
a = np.array([[5,2,7],[4,1,8],[11,17,25]])

In [11]:
a

array([[ 5,  2,  7],
       [ 4,  1,  8],
       [11, 17, 25]])

In [12]:
a.shape

(3, 3)

In [13]:
a.mean()

8.88888888888889

In [15]:
b = np.random.randn(5,5)
b

array([[-1.79961995,  0.45802948, -0.19656782, -1.95689968,  0.41916431],
       [ 0.57549716,  0.6139438 ,  0.18345451,  0.65730429,  0.48497279],
       [ 0.60519808,  1.42486582, -0.99943178, -0.30026154,  1.10333606],
       [-0.60260818, -0.07113552, -0.3818648 , -0.70580458, -1.6122502 ],
       [ 0.25448193, -0.22246388, -0.99188238, -1.4742657 ,  0.04429054]])

In [16]:
b.shape

(5, 5)

In [14]:
import pandas as pd

In [17]:
c = pd.DataFrame(b)

In [18]:
c

0         1         2         3         4
0 -1.799620  0.458029 -0.196568 -1.956900  0.419164
1  0.575497  0.613944  0.183455  0.657304  0.484973
2  0.605198  1.424866 -0.999432 -0.300262  1.103336
3 -0.602608 -0.071136 -0.381865 -0.705805 -1.612250
4  0.254482 -0.222464 -0.991882 -1.474266  0.044291

In [20]:
df = pd.read_csv('iris.csv')

In [21]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [23]:
df1 = pd.read_csv(r'C:\Users\hp\Desktop\iris.csv')

In [26]:
df1.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [25]:
df.shape

(150, 5)

In [31]:
pd.set_option('display.max_rows',150)

In [32]:
df1

sepal.length  sepal.width  petal.length  petal.width     variety
0             5.1          3.5           1.4          0.2      Setosa
1             4.9          3.0           1.4          0.2      Setosa
2             4.7          3.2           1.3          0.2      Setosa
3             4.6          3.1           1.5          0.2      Setosa
4             5.0          3.6           1.4          0.2      Setosa
5             5.4          3.9           1.7          0.4      Setosa
6             4.6          3.4           1.4          0.3      Setosa
7             5.0          3.4           1.5          0.2      Setosa
8             4.4          2.9           1.4          0.2      Setosa
9             4.9          3.1           1.5          0.1      Setosa
10            5.4          3.7           1.5          0.2      Setosa
11            4.8          3.4           1.6          0.2      Setosa
12            4.8          3.0           1.4          0.1      Setosa
13            4.3          3.0           1.1          0.1      Setosa
14            5.8          4.0           1.2          0.2      Setosa
15            5.7          4.4           1.5          0.4      Setosa
16            5.4          3.9           1.3          0.4      Setosa
17            5.1          3.5           1.4          0.3      Setosa
18            5.7          3.8           1.7          0.3      Setosa
19            5.1          3.8           1.5          0.3      Setosa
20            5.4          3.4           1.7          0.2      Setosa
21            5.1          3.7           1.5          0.4      Setosa
22            4.6          3.6           1.0          0.2      Setosa
23            5.1          3.3           1.7          0.5      Setosa
24            4.8          3.4           1.9          0.2      Setosa
25            5.0          3.0           1.6          0.2      Setosa
26            5.0          3.4           1.6          0.4      Setosa
27            5.2          3.5           1.5          0.2      Setosa
28            5.2          3.4           1.4          0.2      Setosa
29            4.7          3.2           1.6          0.2      Setosa
30            4.8          3.1           1.6          0.2      Setosa
31            5.4          3.4           1.5          0.4      Setosa
32            5.2          4.1           1.5          0.1      Setosa
33            5.5          4.2           1.4          0.2      Setosa
34            4.9          3.1           1.5          0.2      Setosa
35            5.0          3.2           1.2          0.2      Setosa
36            5.5          3.5           1.3          0.2      Setosa
37            4.9          3.6           1.4          0.1      Setosa
38            4.4          3.0           1.3          0.2      Setosa
39            5.1          3.4           1.5          0.2      Setosa
40            5.0          3.5           1.3          0.3      Setosa
41            4.5          2.3           1.3          0.3      Setosa
42            4.4          3.2           1.3          0.2      Setosa
43            5.0          3.5           1.6          0.6      Setosa
44            5.1          3.8           1.9          0.4      Setosa
45            4.8          3.0           1.4          0.3      Setosa
46            5.1          3.8           1.6          0.2      Setosa
47            4.6          3.2           1.4          0.2      Setosa
48            5.3          3.7           1.5          0.2      Setosa
49            5.0          3.3           1.4          0.2      Setosa
50            7.0          3.2           4.7          1.4  Versicolor
51            6.4          3.2           4.5          1.5  Versicolor
52            6.9          3.1           4.9          1.5  Versicolor
53            5.5          2.3           4.0          1.3  Versicolor
54            6.5          2.8           4.6          1.5  Versicolor
55            5.7          2.8           4.5          1.3  Versicolor
56            6